### ISSUE TITLE
Steam Apps Manager crashes when an ACF file contains "appID" instead of "appid"

### ISSUE THREAD

**Issue by martinvonwittich** [natinusala/Steam-Apps-Manager#1]
Hi,

on my computer Steam Apps Manager wouldn't start at all. I've looked into the event log and found the following stack trace:

<pre>
Protokollname: Application
Quelle:        .NET Runtime
Datum:         02.01.2017 00:08:20
Ereignis-ID:   1026
Aufgabenkategorie:Keine
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      DESKTOP-Q6QP05F
Beschreibung:
Anwendung: Steam.Apps.Manager.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Collections.Generic.KeyNotFoundException
   bei System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(System.__Canon)
   bei Steam_Apps_Manager.SteamUtils.App..ctor(System.String, Steam_Apps_Manager.SteamUtils.LibraryFolder)
   bei Steam_Apps_Manager.SteamUtils.LibraryFolder..ctor(System.String)
   bei Steam_Apps_Manager.SteamUtils.LibraryFolder.GetAllLibraryFolders()
   bei Steam_Apps_Manager.MainWindow.RefreshApps()
   bei Steam_Apps_Manager.MainWindow.Window_Initialized(System.Object, System.EventArgs)
   bei System.Windows.FrameworkElement.RaiseInitialized(System.Windows.EventPrivateKey, System.EventArgs)
   bei System.Windows.FrameworkElement.OnInitialized(System.EventArgs)
   bei System.Windows.FrameworkElement.TryFireInitialized()
   bei System.Windows.FrameworkElement.EndInit()
   bei MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(System.Xaml.XamlType, System.Object, Boolean)

...
</pre>

I looked into the source code and figured out that Steam Apps Manager apparently tries to parse the *.acf files in the steamapps directories, and the bug is probably in one of these lines in App.cs where it is trying to use the key/value pairs parsed from the file:

<pre>
        public App(string manifestPath, LibraryFolder directory)
        {
            this.manifestPath = manifestPath;
            this.folder = directory;

            ACFNode appState = (ACFNode) ACFNode.ParseACF(manifestPath)["AppState"];

            this.appId = uint.Parse(((string)appState["appid"]));
            this.appName = (string)appState["name"];
            this.installDir = (string)appState["installdir"];
            this.fullInstallDir = this.folder.path + "\\common\\" + installDir;
            this.appState = int.Parse((string)appState["StateFlags"]);
</pre>

I separated my *.acf files into "files that do crash Steam Apps Manager" and "files that don't crash Steam Apps Manager" by moving them all into a separate folder and then moving them back one by one, and always trying to launch it after each file. The thing that all bad acf files have in common is an uppercase "appID" key, for example `appmanifest_6910.acf`:

<pre>
"AppState"
{
	"appID"		"6910"
	"Universe"		"1"
	"name"		"Deus Ex: Game of the Year Edition"
	"StateFlags"		"4"
	"installdir"		"Deus Ex"
	"LastUpdated"		"1457457544"
	"UpdateResult"		"0"
	"SizeOnDisk"		"754793921"
	"buildid"		"251801"
	"LastOwner"		"76561197971573782"
	"BytesToDownload"		"421978512"
	"BytesDownloaded"		"97264"
	"AutoUpdateBehavior"		"0"
	"AllowOtherDownloadsWhileRunning"		"0"
	"UserConfig"
	{
		"language"		"english"
	}
	"MountedDepots"
	{
		"6911"		"8456979172979270170"
	}
}
</pre>

I'd suggest the following changes:
- parse the ACF files case insensitively, as Steam probably does this too
- ignore ACF files that can't be properly parsed instead of crashing

**Comment by natinusala** [comment]
Hi,

Thanks a lot for this investigation ! I'll fix it ASAP, it looks like the case insensitive ACF parsing is the solution here.

**Comment by natinusala** [comment]
It should be resolved since version 1.0.1.
