### ISSUE TITLE
Size is 0 for all games

### ISSUE THREAD

**Issue by ElPumpo** [natinusala/Steam-Apps-Manager#3]
I have no clue on what's going on, Steam Apps Manager says that all games are 0 B. They're obviously not.

Win10 AU

**Comment by natinusala** [comment]
I noticed that too. It doesn't really matter since Steam now officially supports moving games from the properties menu. Do you still want me to fix this issue ?

**Comment by ElPumpo** [comment]
It's up to you, I'd do it and call it the final release.

**Comment by natinusala** [comment]
I'll look for it then.
